version: '3.7'

services:
  spring-boot-service:
    container_name: boot-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - database-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-service/database?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_DATABASEPLATFORM: org.hibernate.dialect.MySQL5Dialect


  database-service:
    container_name: db-container
    image: mysql/mysql-server:8.0.19
    ports:
      - 3306:306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root